"""Add website_url to Feed model

Revision ID: 3f3842ba0b5c
Revises:
Create Date: 2025-06-14 20:03:24.907205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3842ba0b5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('fetched_time', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_items_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_items_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_items_published_time'), ['published_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_items_published_time'))
        batch_op.drop_index(batch_op.f('ix_feed_items_is_read'))
        batch_op.drop_index(batch_op.f('ix_feed_items_feed_id'))

    op.drop_table('feed_items')
    op.drop_table('feeds')
    op.drop_table('tabs')
    # ### end Alembic commands ###
