"""Initial multi-user schema

Revision ID: 4b661de73f6e
Revises:
Create Date: 2026-02-22 17:42:49.108783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b661de73f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('site_link', sa.String(length=500), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds')),
    sa.UniqueConstraint('url', name=op.f('uq_feeds_url'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('fetched_time', sa.DateTime(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_feed_items_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_items')),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_feed_item_feed_id_guid')
    )
    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_items_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index('ix_feed_items_feed_id_published_fetched_time', ['feed_id', 'published_time', 'fetched_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_items_published_time'), ['published_time'], unique=False)

    op.create_table('tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tabs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tabs')),
    sa.UniqueConstraint('user_id', 'name', name='uq_tab_user_id_name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_subscriptions_feed_id_feeds')),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], name=op.f('fk_subscriptions_tab_id_tabs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('user_id', 'feed_id', name='uq_subscription_user_id_feed_id')
    )
    op.create_table('user_item_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['feed_items.id'], name=op.f('fk_user_item_states_item_id_feed_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_item_states_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_item_states')),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item_state_user_id_item_id')
    )
    with op.batch_alter_table('user_item_states', schema=None) as batch_op:
        batch_op.create_index('ix_user_item_states_user_id_is_read', ['user_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item_states', schema=None) as batch_op:
        batch_op.drop_index('ix_user_item_states_user_id_is_read')

    op.drop_table('user_item_states')
    op.drop_table('subscriptions')
    op.drop_table('tabs')
    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_items_published_time'))
        batch_op.drop_index('ix_feed_items_feed_id_published_fetched_time')
        batch_op.drop_index(batch_op.f('ix_feed_items_feed_id'))

    op.drop_table('feed_items')
    op.drop_table('users')
    op.drop_table('feeds')
    # ### end Alembic commands ###
