"""Fix guid unique constraint to be per-feed

Revision ID: 14d8ad95ac2e
Revises: 44ddebc82c69
Create Date: 2026-01-26 02:19:13.414286

"""

import sqlalchemy as sa
from alembic import op

from backend.migration_helpers import safe_drop_constraint

# revision identifiers, used by Alembic.
revision = "14d8ad95ac2e"
down_revision = "44ddebc82c69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("feed_items", schema=None) as batch_op:
        # Drop the named constraint safely if it exists (handles re-runs or different states)
        safe_drop_constraint("feed_items",
                             "uq_feed_items_guid",
                             type_="unique",
                             batch_op=batch_op)

        # We need to drop the old global unique constraint on 'guid'.
        # Since it was unnamed in the initial migration, SQLite/Alembic might struggle.
        # In batch mode, we explicitly omit it from the new table definition
        # by calling drop_constraint with columns=['guid'].
        try:
            batch_op.drop_constraint(None, type_="unique", columns=["guid"])
        except Exception:
            pass

        batch_op.create_unique_constraint("uq_feed_items_feed_id_guid",
                                          ["feed_id", "guid"])
        batch_op.create_index(
            "ix_feed_items_feed_id_published_fetched_time",
            ["feed_id", "published_time", "fetched_time"],
            unique=False,
        )

    with op.batch_alter_table("tabs", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_tabs_name", ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tabs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_tabs_name", type_="unique")

    with op.batch_alter_table("feed_items", schema=None) as batch_op:
        batch_op.drop_index("ix_feed_items_feed_id_published_fetched_time")
        batch_op.drop_constraint("uq_feed_items_feed_id_guid", type_="unique")

    # ### end Alembic commands ###
