"""Add index to Feed.tab_id

Revision ID: 6d64ea28d32d
Revises: 14d8ad95ac2e
Create Date: 2026-04-13 22:03:45.080599

"""

import sqlalchemy as sa
from alembic import op

from backend.migration_helpers import constraint_exists, safe_drop_constraint

# revision identifiers, used by Alembic.
revision = "6d64ea28d32d"
down_revision = "14d8ad95ac2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feeds_tab_id"), [
                              "tab_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feeds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feeds_tab_id"))

    # ### end Alembic commands ###
