"""Add site_url to Feed model

Revision ID: 7a6429ce2d26
Revises: 996291c6a151
Create Date: 2025-06-21 13:28:29.685030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6429ce2d26'
down_revision = '996291c6a151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('site_url')

    # ### end Alembic commands ###
