"""Add index to Feed url

Revision ID: fd5298e77490
Revises: 14d8ad95ac2e
Create Date: 2026-03-26 22:52:28.138848

"""
from alembic import op
import sqlalchemy as sa
from backend.migration_helpers import safe_drop_constraint, constraint_exists


# revision identifiers, used by Alembic.
revision = 'fd5298e77490'
down_revision = '14d8ad95ac2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeds_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeds_url'))

    # ### end Alembic commands ###
